ci: fix release build commands
The generated sources are skipped:

Error: ovsdb/ovsdb.go:37:21: undefined: ovs.FullDatabaseModel
Error: ovsdb/ovsdb.go:42:42: undefined: ovs.Schema
Error: Process completed with exit code 1.

Use make to build.

Fixes: 924f874ecd1d ("ci: add release workflow to publish binaries on git tags")
Signed-off-by: Robin Jarry <rjarry@redhat.com>